version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: delivery_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: delivery-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge